runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: app.app